SecondBrainPlanner/SecondBrain

app/build.gradle.kts
app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.kt
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_new_task_sheet.xml
app/src/main/res/values/strings.xml
build.gradle.kts
gradle/libs.versions.toml

java version von 1.8 auf 17
view binding aktiviert
button press löst öffnen von einem fenster zum eingeben von aufgaben-name und beschreibung aus

4 add button press action add item UI

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.kt
app/src/main/java/io/github/secondbrainplanner/Task.java
app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/item_task.xml

added Task class and xml, task adapter
- task class as data (individual task)
- task xml as task layout for each individual task in recyclerView
- task adapter as manager between tasks and recyclerView

1 recycler view adapter

---

app/src/main/java/io/github/secondbrainplanner/DatabaseManager.java
app/src/main/java/io/github/secondbrainplanner/TaskManager.java

Datenbankmanagerklasse hinzugefügt
Taskmanagerklasse hinzugefügt
Datenbank wird automatisch auf dem Gerät erstellt, sobald der erste Eintrag eingefügt wird

6 database creation on device

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
app/src/main/java/io/github/secondbrainplanner/Task.java
app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/TaskManager.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModelFactory.java

Datenbank ist nun integriert. Die App speichert und läd die Daten automatisch in bzw. aus der Datenbank. Zeitstempel sind noch nicht korrekt, da diese noch nicht im GUI integiert sind.

12 database integration

---

app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/res/layout/item_task.xml

date sectioning of tasks in recycler view

14 date sectioning in recycler view

---

app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
app/src/main/res/layout/fragment_new_task_sheet.xml

Datum kann jetzt ausgewählt werden und wird auch mit gespeichert.

19 integrate date picker in newtasksheet

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java

- Aufgaben Listen logik geändert, sodass sowohl seitstempel als auch aufgaben angezeigt werden können
- code refactoring um die logik bei nutzung von objekten beizubehalten

15 recycler view shows future date sections

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java

zeitstempel werden nun angepasst auf die Aufgaben welche weiter in der Zukunft liegen als 30 tage 

23 show tasks older than 30 days

---

app/src/main/java/io/github/secondbrainplanner/EditTaskSheet.java
app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
app/src/main/res/layout/fragment_edit_task_sheet.xml
app/src/main/res/layout/fragment_new_task_sheet.xml

Es ist jetzt möglich, auf ein Task zu klicken um diesen zu editieren. Der angeklickte Task wird an die EditTaskSheet Klasse übergeben. In der TaskViewModel Klasse wurde eine editTask Funktion eingebaut.

27 edit tasks

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/res/drawable/bottom_border.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/item_task.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/themes.xml

new standard dark design, timestamps now are underlined 

26 design enhancement

---

app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java

zeitstempel werden nun hervorgehoben, wenn ein task an dem tag vorhanden ist

30 timestamp layout change on tasks

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/res/layout/activity_main.xml

horizontal top bar to indicate the day of the week from the top timestamp of the task list (recycler view)

32 day of the week view

---

app/src/main/java/io/github/secondbrainplanner/EditTaskSheet.java
app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
app/src/main/res/values/styles.xml

NewTaskSheet und EditTaskSheet sind nun vollständig sichtbar, wenn sie geöffnet werden.

38 bottom sheets fragments full screen on launch

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/res/layout/activity_main.xml

main xml:
month and year added to the top
main java:
checking on scroll and getting top position information / then getting the date in specific format and showing it as string in top left corner

month and year now appearing in the top left corner

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/res/layout/activity_main.xml

numbers row under daysOfTheWeek row to see the day number corresponding to the dayOfTheWeek

added numbers row under day of week row which is matching the current week day numbers

---

app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/item_task.xml
app/src/main/res/values/colors.xml

50 layout and design improvements

---

app/src/main/java/io/github/secondbrainplanner/DatabaseManager.java
app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java
app/src/main/res/layout/activity_settings.xml

Die Datenbank kann über die Einstellungen in eine CSV Datei exportiert werden

34 export database to csv file

---

app/src/main/java/io/github/secondbrainplanner/DatabaseManager.java
app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java

Man kann nun eine Datenbank importieren. Nach einem erfolgreichen Importvorgang, wird die App neu gestartet

added import func

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java

Beim Aufrufen von NewTaskSheet muss jetzt ein Datum übergeben werden. Dieses wird durch den OnScrollListener geholt und ist immer das vom aktuellen View.

added button date picker always shows selected date

---

app/src/main/res/drawable/bottom_border.xml
app/src/main/res/layout/item_task.xml

46 line under timestamp not showing on different resolution

---

app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/TaskManager.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/item_task.xml

Man kann nun Tasks abhaken, diese verschwinden dann aus der Übersicht. Abgehakte Tasks werden in der Datenbank als erledigt markiert und der Timestamp wird abgespeichert.

33 complete tasks

---

app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java

Die App kann nun in den Einstellungen zurückgesetzt werden. Dabei wird die Datenbank gelöscht und danach die App neugestartet. Für das Neustarten gibt es jetzt eine extra Funktion.

App reset in settings

---

app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_edit_task_sheet.xml
app/src/main/res/layout/fragment_new_task_sheet.xml
app/src/main/res/values-night/themes.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/themes.xml

- color adjustments on recyclerView, top bar and floating action button
- layout alignment improvements on task sheets

63 slight layout adjustments

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/secondbrainplanner/CompletedTaskActivity.java
app/src/main/java/io/github/secondbrainplanner/CompletedTaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/TaskManager.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java
app/src/main/res/drawable/check_box.xml
app/src/main/res/layout/activity_completed_tasks.xml
app/src/main/res/layout/item_completedtask.xml
app/src/main/res/menu/toolbar_menu.xml

Der Screen für die Erledigten Aufgaben funktioniert nun. Im Screen sieht man die Aufgabe, die Beschreibung und wann man sie erledigt hat. Sobald man ein Task abhakt, verschwindet dieser nun sofort aus der Übersicht. Die Datenbankabfrage wurde leicht verbessert. 

67 screen for completed task

---

app/src/main/java/io/github/secondbrainplanner/CompletedTaskActivity.java
app/src/main/java/io/github/secondbrainplanner/CompletedTaskAdapter.java
app/src/main/res/layout/activity_completed_tasks.xml
app/src/main/res/layout/activity_settings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

layout and color of toolbar activities adjusted to match with app design

73 toolbar activities layout adjustment

---

app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/java/io/github/secondbrainplanner/SettingsActivity.java
app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/res/values-de/strings.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

Toasts und Alertboxen sind jetzt nicht mehr auf Deutsch hardcoded.

updated toast & alert strings

---

app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java

unchecked old task will now all be shown on top without a timestamp

76 mangegament for old tasks

---

app/src/main/java/io/github/secondbrainplanner/CompletedTaskActivity.java

unchecking tasks which were checked while being in the past now are not able to get to the past date again (min. date is today)

unchecking checked tasks: fixed time travel bug 

---

app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java

tasks of the past will now be highlighted in red

tasks of the past will now be highlighted in red

---

app/src/main/java/io/github/secondbrainplanner/NotificationHelper.java

Man kann jetzt auf die Notifications klicken und die App wird direkt gestartet (geht auch wenn die App im Hintergrund geschlossen wird)

click on notification

---

app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/res/layout/item_task.xml

when reminder is set, it will show the time in the recycler view 

85 task show reminder time

---

app/src/main/java/io/github/secondbrainplanner/CompletedTaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/EditTaskSheet.java
app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
app/src/main/res/values-de/strings.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

- Wenn man die App startet und direkt eine Task erstellt, steht nun immer das heutige Datum drin.
- Die Beschreibungen dürfen jetzt leer sein.
- Wenn man kein Datum oder Name angegeben hat, bekommt man eine Toast-Nachricht.
- Bei den Erledigten Aufgaben sieht man jetzt von wann die Task ursprünglich war.

general improvements

---

app/src/main/java/io/github/secondbrainplanner/CompletedTaskActivity.java
app/src/main/java/io/github/secondbrainplanner/TaskViewModel.java

- Man bekommt jetzt bei alten Tasks keine Notifcation mehr
- Man bekommt keine Notification mehr, wenn die Uhrzeit in der Vergangenheit liegt

91 notification on uncomplete older tasks

---

app/src/main/java/io/github/secondbrainplanner/EditTaskSheet.java
app/src/main/java/io/github/secondbrainplanner/NewTaskSheet.java
app/src/main/res/layout/fragment_edit_task_sheet.xml
app/src/main/res/layout/fragment_new_task_sheet.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

added option to delete reminder / added strings to strings file

93 option to delete reminder

---

app/src/main/java/io/github/secondbrainplanner/FilterTaskAdapter.java
app/src/main/java/io/github/secondbrainplanner/MainActivity.java
app/src/main/res/drawable/filter.xml
app/src/main/res/menu/toolbar_menu.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-en/strings.xml
app/src/main/res/values/strings.xml

Der Filter kann nun aktiviert werden und es werden nurnoch Tage angezeigt, die auch eine Task haben.

filter option

---

app/src/main/java/io/github/secondbrainplanner/TaskAdapter.java
app/src/main/res/layout/item_task.xml

Saturday / Sunday are now bold instead of italic

Saturday / Sunday are now bold instead of italic
